Repository fabric8-services/toolchain-operator, pull requests merged in 2019-05, with the labels that each got.

#53 add owners to be used by openshift ci
  OWNERS
Labels: size/S

#54 remove centos ci setup
  cico_build_deploy.sh
  cico_run_coverage.sh
  cico_run_tests.sh
  cico_setup.sh
Labels: approved, size/L

#55 fix e2e flow
  Dockerfile.dev
  OWNERS
  make/dev.mk
  pkg/cluster/config.go
Labels: approved, lgtm, size/S

#56 chore: update readme with more detailed overview
  README.adoc
  pkg/controller/toolchainenabler/toolchainenabler_controller.go
Labels: approved, lgtm, size/S

#57 adds steps to configure cluster to be used by toolchain
  hack/setup.bash
Labels: approved, lgtm, size/M

#59 remove obsolete links from README.adoc
  README.adoc
Labels: approved, lgtm, size/XS
